LCID = {
    "0x0409": {
        "iso_code": "us",
        "tray_name": "Keyboard Layout",
        "exit": "Exit",
        "position": "Position",
        "options": "Options",
        "run_at_startup": "Run at startup",
        "about": "About",
        "top_left": "Top Left",
        "bottom_left": "Bottom Left",
        "top_right": "Top Right",
        "bottom_right": "Bottom Right",
        "top_center": "Top Center",
        "bottom_center": "Bottom Center",
        "center": "Center"
    },
    "0x0809": {
        "iso_code": "gb",
        "tray_name": "Keyboard Layout",
        "exit": "Exit",
        "position": "Position",
        "options": "Options",
        "run_at_startup": "Run at startup",
        "about": "About",
        "top_left": "Top Left",
        "bottom_left": "Bottom Left",
        "top_right": "Top Right",
        "bottom_right": "Bottom Right",
        "top_center": "Top Center",
        "bottom_center": "Bottom Center",
              "center": "Center"
         },
    "0x0422": {
        "iso_code": "ua",
        "tray_name": "Розкладка клавіатури",
        "exit": "Вихід",
        "position": "Положення",
        "options": "Опції",
        "run_at_startup": "Запускати при старті",
        "about": "Про програму",
        "top_left": "Згори Зліва",
        "bottom_left": "Знизу Зліва",
        "top_right": "Згори Справа",
        "bottom_right": "Знизу Справа",
        "top_center": "Згори По Центру",
        "bottom_center": "Знизу По Центру",
              "center": "Центр"
         },
    "0x0419": {
        "iso_code": "ru",
        "tray_name": "Раскладка клавиатуры",
        "exit": "Выход",
        "position": "Позиция",
        "options": "Опции",
        "run_at_startup": "Запускать при старте",
        "about": "О программе",
        "top_left": "Сверху Слева",
        "bottom_left": "Снизу Слева",
        "top_right": "Сверху Справа",
        "bottom_right": "Снизу Справа",
        "top_center": "Сверху По Центру",
        "bottom_center": "Снизу По Центру",
              "center": "Центр"
         },
    "0x040c": {
        "iso_code": "fr",
        "tray_name": "Disposition du clavier",
        "exit": "Quitter",
        "position": "Position",
        "options": "Options",
        "run_at_startup": "Démarrer au lancement",
        "about": "À propos",
        "top_left": "En Haut à Gauche",
        "bottom_left": "En Bas à Gauche",
        "top_right": "En Haut à Droite",
        "bottom_right": "En Bas à Droite",
        "top_center": "En Haut au Centre",
        "bottom_center": "En Bas au Centre",
              "center": "Centre"
         },
    "0x0407": {
        "iso_code": "de",
        "tray_name": "Tastaturlayout",
        "exit": "Beenden",
        "position": "Position",
        "options": "Optionen",
        "run_at_startup": "Beim Start ausführen",
        "about": "Über",
        "top_left": "Oben Links",
        "bottom_left": "Unten Links",
        "top_right": "Oben Rechts",
        "bottom_right": "Unten Rechts",
        "top_center": "Oben Mitte",
        "bottom_center": "Unten Mitte",
              "center": "Mitte"
         },
    "0x040a": {
        "iso_code": "es",
        "tray_name": "Distribución del teclado",
        "exit": "Salir",
        "position": "Posición",
        "options": "Opciones",
        "run_at_startup": "Ejecutar al inicio",
        "about": "Acerca de",
        "top_left": "Arriba Izquierda",
        "bottom_left": "Abajo Izquierda",
        "top_right": "Arriba Derecha",
        "bottom_right": "Abajo Derecha",
        "top_center": "Arriba Centro",
        "bottom_center": "Abajo Centro",
              "center": "Centro"
         },
    "0x0410": {
        "iso_code": "it",
        "tray_name": "Layout Tastiera",
        "exit": "Esci",
        "position": "Posizione",
        "options": "Opzioni",
        "run_at_startup": "Esegui all'avvio",
        "about": "Informazioni",
        "top_left": "In Alto a Sinistra",
        "bottom_left": "In Basso a Sinistra",
        "top_right": "In Alto a Destra",
        "bottom_right": "In Basso a Destra",
        "top_center": "In Alto al Centro",
        "bottom_center": "In Basso al Centro",
              "center": "Centro"
         },
    "0x0415": {
        "iso_code": "pl",
        "tray_name": "Układ klawiatury",
        "exit": "Wyjście",
        "position": "Pozycja",
        "options": "Opcje",
        "run_at_startup": "Uruchom przy starcie",
        "about": "O programie",
        "top_left": "Góra Lewo",
        "bottom_left": "Dół Lewo",
        "top_right": "Góra Prawo",
        "bottom_right": "Dół Prawo",
        "top_center": "Góra Środek",
        "bottom_center": "Dół Środek",
              "center": "Środek"
         },
    "0x0411": {
        "iso_code": "jp",
        "tray_name": "キーボードレイアウト",
        "exit": "終了",
        "position": "位置",
        "options": "オプション",
        "run_at_startup": "スタートアップで実行",
        "about": "情報",
        "top_left": "左上",
        "bottom_left": "左下",
        "top_right": "右上",
        "bottom_right": "右下",
        "top_center": "上中央",
        "bottom_center": "下中央",
              "center": "中央"
         },
    "0x0804": {
        "iso_code": "cn",
        "tray_name": "键盘布局",
        "exit": "退出",
        "position": "位置",
        "options": "选项",
        "run_at_startup": "开机运行",
        "about": "关于",
        "top_left": "左上角",
        "bottom_left": "左下角",
        "top_right": "右上角",
        "bottom_right": "右下角",
        "top_center": "顶部居中",
        "bottom_center": "底部居中"
    },
    "0x0403": {
        "iso_code": "catalonia",
        "tray_name": "Distribució del teclat",
        "exit": "Sortir",
        "position": "Posició",
        "options": "Opcions",
        "run_at_startup": "Executar a l'inici",
        "about": "Sobre",
        "top_left": "A Dalt a l'Esquerra",
        "bottom_left": "A Baix a l'Esquerra",
        "top_right": "A Dalt a la Dreta",
        "bottom_right": "A Baix a la Dreta",
        "top_center": "A Dalt al Centre",
        "bottom_center": "A Baix al Centre"
    },
    "0x0405": {
        "iso_code": "cz",
        "tray_name": "Rozložení klávesnice",
        "exit": "Ukončit",
        "position": "Pozice",
        "options": "Možnosti",
        "run_at_startup": "Spustit při startu",
        "about": "O aplikaci",
        "top_left": "Nahoře Vlevo",
        "bottom_left": "Dole Vlevo",
        "top_right": "Nahoře Vpravo",
        "bottom_right": "Dole Vpravo",
        "top_center": "Nahoře Střed",
        "bottom_center": "Dole Střed"
    },
    "0x0406": {
        "iso_code": "dk",
        "tray_name": "Tastaturlayout",
        "exit": "Afslut",
        "position": "Position",
        "options": "Muligheder",
        "run_at_startup": "Kør ved opstart",
        "about": "Om",
        "top_left": "Øverst Til Venstre",
        "bottom_left": "Nederst Til Venstre",
        "top_right": "Øverst Til Højre",
        "bottom_right": "Nederst Til Højre",
        "top_center": "Øverst I Midten",
        "bottom_center": "Nederst I Midten"
    },
    "0x0425": {
        "iso_code": "ee",
        "tray_name": "Klaviatuuri paigutus",
        "exit": "Välju",
        "position": "Asukoht",
        "options": "Valikud",
        "run_at_startup": "Käivita käivitamisel",
        "about": "Teave",
        "top_left": "Üleval Vasakul",
        "bottom_left": "All Vasakul",
        "top_right": "Üleval Paremal",
        "bottom_right": "All Paremal",
        "top_center": "Üleval Keskel",
        "bottom_center": "All Keskel"
    },
    "0x0408": {
        "iso_code": "gr",
        "tray_name": "Διάταξη πληκτρολογίου",
        "exit": "Έξοδος",
        "position": "Θέση",
        "options": "Επιλογές",
        "run_at_startup": "Εκτέλεση στην εκκίνηση",
        "about": "Σχετικά",
        "top_left": "Πάνω Αριστερά",
        "bottom_left": "Κάτω Αριστερά",
        "top_right": "Πάνω Δεξιά",
        "bottom_right": "Κάτω Δεξιά",
        "top_center": "Πάνω Κέντρο",
        "bottom_center": "Κάτω Κέντρο"
    },
    "0x040E": {
        "iso_code": "hu",
        "tray_name": "Billentyűzet-elrendezés",
        "exit": "Kilépés",
        "position": "Pozíció",
        "options": "Opciók",
        "run_at_startup": "Indításkor futtatás",
        "about": "Névjegy",
        "top_left": "Bal Fent",
        "bottom_left": "Bal Lent",
        "top_right": "Jobb Fent",
        "bottom_right": "Jobb Lent",
        "top_center": "Fent Középen",
        "bottom_center": "Lent Középen"
    },
    "0x0412": {
        "iso_code": "kr",
        "tray_name": "키보드 레이아웃",
        "exit": "종료",
        "position": "위치",
        "options": "옵션",
        "run_at_startup": "시작 시 실행",
        "about": "정보",
        "top_left": "왼쪽 상단",
        "bottom_left": "왼쪽 하단",
        "top_right": "오른쪽 상단",
        "bottom_right": "오른쪽 하단",
        "top_center": "상단 중앙",
        "bottom_center": "하단 중앙"
    },
    "0x0427": {
        "iso_code": "lt",
        "tray_name": "Klaviatūros išdėstymas",
        "exit": "Išeiti",
        "position": "Pozicija",
        "options": "Parinktys",
        "run_at_startup": "Paleisti paleidus",
        "about": "Apie",
        "top_left": "Viršuje Kairėje",
        "bottom_left": "Apačioje Kairėje",
        "top_right": "Viršuje Dešinėje",
        "bottom_right": "Apačioje Dešinėje",
        "top_center": "Viršuje Centre",
        "bottom_center": "Apačioje Centre"
    },
    "0x0413": {
        "iso_code": "nl",
        "tray_name": "Toetsenbordindeling",
        "exit": "Afsluiten",
        "position": "Positie",
        "options": "Opties",
        "run_at_startup": "Start bij opstarten",
        "about": "Over",
        "top_left": "Linksboven",
        "bottom_left": "Linksonder",
        "top_right": "Rechtsboven",
        "bottom_right": "Rechtsonder",
        "top_center": "Midden Boven",
        "bottom_center": "Midden Onder"
    },
    "0x0414": {
        "iso_code": "no",
        "tray_name": "Tastaturoppsett",
        "exit": "Avslutt",
        "position": "Posisjon",
        "options": "Alternativer",
        "run_at_startup": "Kjør ved oppstart",
        "about": "Om",
        "top_left": "Topp Venstre",
        "bottom_left": "Bunn Venstre",
        "top_right": "Topp Høyre",
        "bottom_right": "Bunn Høyre",
        "top_center": "Topp Senter",
        "bottom_center": "Bunn Senter"
    },
    "0x041D": {
        "iso_code": "se",
        "tray_name": "Tangentbordslayout",
        "exit": "Avsluta",
        "position": "Position",
        "options": "Alternativ",
        "run_at_startup": "Kör vid start",
        "about": "Om",
        "top_left": "Övre Vänster",
        "bottom_left": "Nedre Vänster",
        "top_right": "Övre Höger",
        "bottom_right": "Nedre Höger",
        "top_center": "Övre Mitten",
        "bottom_center": "Nedre Mitten"
    },
    "0x041B": {
        "iso_code": "sk",
        "tray_name": "Rozloženie klávesnice",
        "exit": "Ukončiť",
        "position": "Pozícia",
        "options": "Možnosti",
        "run_at_startup": "Spustiť pri štarte",
        "about": "O aplikácii",
        "top_left": "Hore Vľavo",
        "bottom_left": "Dole Vľavo",
        "top_right": "Hore Vpravo",
        "bottom_right": "Dole Vpravo",
        "top_center": "Hore Stred",
        "bottom_center": "Dole Stred"
    },
    "0x041F": {
        "iso_code": "tr",
        "tray_name": "Klavye Düzeni",
        "exit": "Çıkış",
        "position": "Konum",
        "options": "Seçenekler",
        "run_at_startup": "Başlangıçta Çalıştır",
        "about": "Hakkında",
        "top_left": "Sol Üst",
        "bottom_left": "Sol Alt",
        "top_right": "Sağ Üst",
        "bottom_right": "Sağ Alt",
        "top_center": "Üst Orta",
        "bottom_center": "Alt Orta"
    },
    "0x0401": {
        "iso_code": "sa",
        "exit": "خروج",
        "position": "الموقع",
        "run_at_startup": "تشغيل عند بدء التشغيل",
        "about": "حول",
        "top_left": "أعلى اليسار",
        "bottom_left": "أسفل اليسار",
        "top_right": "أعلى اليمين",
        "bottom_right": "أسفل اليمين",
        "top_center": "أعلى الوسط",
        "bottom_center": "أسفل الوسط"
    },
    "0x041A": {
        "iso_code": "hr",
        "exit": "Izlaz",
        "position": "Pozicija",
        "run_at_startup": "Pokreni pri pokretanju",
        "about": "O programu",
        "top_left": "Gore Lijevo",
        "bottom_left": "Dole Lijevo",
        "top_right": "Gore Desno",
        "bottom_right": "Dole Desno",
        "top_center": "Gore Centar",
        "bottom_center": "Dole Centar"
    },
    "0x0416": {
        "iso_code": "br",
        "exit": "Sair",
        "position": "Posição",
        "run_at_startup": "Executar na inicialização",
        "about": "Sobre",
        "top_left": "Superior Esquerdo",
        "bottom_left": "Inferior Esquerdo",
        "top_right": "Superior Direito",
        "bottom_right": "Inferior Direito",
        "top_center": "Centro Superior",
        "bottom_center": "Centro Inferior"
    },
    "0x0423": {
        "iso_code": "by",
        "exit": "Выхад",
        "position": "Палажэнне",
        "run_at_startup": "Запускаць пры старце",
        "about": "Пра праграму",
        "top_left": "Зверху Злева",
        "bottom_left": "Знізу Злева",
        "top_right": "Зверху Справа",
        "bottom_right": "Знізу Справа",
        "top_center": "Зверху Па Цэнтры",
        "bottom_center": "Знізу Па Цэнтры"
    },
    "0x0402": {
        "iso_code": "bg",
        "exit": "Изход",
        "position": "Позиция",
        "run_at_startup": "Стартиране при стартиране",
        "about": "За програмата",
        "top_left": "Горе Ляво",
        "bottom_left": "Долу Ляво",
        "top_right": "Горе Дясно",
        "bottom_right": "Долу Дясно",
        "top_center": "Горе Център",
        "bottom_center": "Долу Център"
    },
    "0x0404": {
        "iso_code": "tw",
        "exit": "結束",
        "position": "位置",
        "run_at_startup": "開機執行",
        "about": "關於",
        "top_left": "左上角",
        "bottom_left": "左下角",
        "top_right": "右上角",
        "bottom_right": "右下角",
        "top_center": "上置中",
        "bottom_center": "下置中"
    },
    "0x0418": {
        "iso_code": "ro",
        "exit": "Ieșire",
        "position": "Poziție",
        "run_at_startup": "Rulare la pornire",
        "about": "Despre",
        "top_left": "Sus Stânga",
        "bottom_left": "Jos Stânga",
        "top_right": "Sus Dreapta",
        "bottom_right": "Jos Dreapta",
        "top_center": "Sus Centru",
        "bottom_center": "Jos Centru"
    },
    "0x042A": {
        "iso_code": "vn",
        "exit": "Thoát",
        "position": "Vị trí",
        "run_at_startup": "Chạy khi khởi động",
        "about": "Về",
        "top_left": "Trên Cùng Bên Trái",
        "bottom_left": "Dưới Cùng Bên Trái",
        "top_right": "Trên Cùng Bên Phải",
        "bottom_right": "Dưới Cùng Bên Phải",
        "top_center": "Trên Cùng Chính Giữa",
        "bottom_center": "Dưới Cùng Chính Giữa"
    },
    "0x040B": {
        "iso_code": "fi",
        "exit": "Poistu",
        "position": "Sijainti",
        "run_at_startup": "Käynnistä käynnistyksen yhteydessä",
        "about": "Tietoja",
        "top_left": "Ylä Vasen",
        "bottom_left": "Ala Vasen",
        "top_right": "Ylä Oikea",
        "bottom_right": "Ala Oikea",
        "top_center": "Ylä Keski",
        "bottom_center": "Ala Keski"
    },
    "0x040F": {
        "iso_code": "is",
        "exit": "Hætta",
        "position": "Staða",
        "run_at_startup": "Keyra við ræsingu",
        "about": "Um",
        "top_left": "Efst Vinstri",
        "bottom_left": "Neðst Vinstri",
        "top_right": "Efst Hægri",
        "bottom_right": "Neðst Hægri",
        "top_center": "Efst Miðja",
        "bottom_center": "Neðst Miðja"
    },
    "0x0426": {
        "iso_code": "lv",
        "exit": "Iziet",
        "position": "Pozīcija",
        "run_at_startup": "Palaist startējot",
        "about": "Par",
        "top_left": "Augšā Pa Kreisi",
        "bottom_left": "Apakšā Pa Kreisi",
        "top_right": "Augšā Pa Labi",
        "bottom_right": "Apakšā Pa Labi",
        "top_center": "Augšā Centrā",
        "bottom_center": "Apakšā Centrā"
    },
    "0x041C": {
        "iso_code": "al",
        "exit": "Dil",
        "position": "Pozicioni",
        "run_at_startup": "Nis në start",
        "about": "Rreth",
        "top_left": "Lart Majtas",
        "bottom_left": "Poshtë Majtas",
        "top_right": "Lart Djathtas",
        "bottom_right": "Poshtë Djathtas",
        "top_center": "Lart Qendër",
        "bottom_center": "Poshtë Qendër"
    },
    "0x042B": {
        "iso_code": "am",
        "exit": "Ելք",
        "position": "Դիրք",
        "run_at_startup": "Միացնել գործարկման ժամանակ",
        "about": "Մասին",
        "top_left": "Վերև Ձախ",
        "bottom_left": "Ներքև Ձախ",
        "top_right": "Վերև Աջ",
        "bottom_right": "Ներքև Աջ",
        "top_center": "Վերև Կենտրոն",
        "bottom_center": "Ներքև Կենտրոն"
    },
    "0x042C": {
        "iso_code": "az",
        "exit": "Çıxış",
        "position": "Mövqe",
        "run_at_startup": "Başlanğıcda işə sal",
        "about": "Haqqında",
        "top_left": "Yuxarı Sol",
        "bottom_left": "Aşağı Sol",
        "top_right": "Yuxarı Sağ",
        "bottom_right": "Aşağı Sağ",
        "top_center": "Yuxarı Mərkəz",
        "bottom_center": "Aşağı Mərkəz"
    },
    "0x0439": {
        "iso_code": "in",
        "exit": "बाहर निकलें",
        "position": "जगह",
        "run_at_startup": "शुरुआत में चलाएँ",
        "about": "बारे में",
        "top_left": "ऊपर बाएँ",
        "bottom_left": "नीचे बाएँ",
        "top_right": "ऊपर दाएँ",
        "bottom_right": "नीचे दाएँ",
        "top_center": "ऊपर केंद्र",
        "bottom_center": "नीचे केंद्र"
    },
    "0x0421": {
        "iso_code": "id",
        "exit": "Keluar",
        "position": "Posisi",
        "run_at_startup": "Jalankan saat memulai",
        "about": "Tentang",
        "top_left": "Kiri Atas",
        "bottom_left": "Kiri Bawah",
        "top_right": "Kanan Atas",
        "bottom_right": "Kanan Bawah",
        "top_center": "Tengah Atas",
        "bottom_center": "Tengah Bawah"
    },
    "0x043A": {
        "iso_code": "mt",
        "exit": "Oħroġ",
        "position": "Pożizzjoni",
        "run_at_startup": "Ħaddem mal-istartjar",
        "about": "Dwar",
        "top_left": "Fuq ix-Xellug",
        "bottom_left": "Isfel ix-Xellug",
        "top_right": "Fuq il-Lemin",
        "bottom_right": "Isfel il-Lemin",
        "top_center": "Fuq iċ-Ċentru",
        "bottom_center": "Isfel iċ-Ċentru"
    },
    "0x0450": {
        "iso_code": "mn",
        "exit": "Гарах",
        "position": "Байрлал",
        "run_at_startup": "Ачаалах үед ажиллуулах",
        "about": "Тухай",
        "top_left": "Дээд Зүүн",
        "bottom_left": "Доод Зүүн",
        "top_right": "Дээд Баруун",
        "bottom_right": "Доод Баруун",
        "top_center": "Дээд Төв",
        "bottom_center": "Доод Төв"
    },
    "0x0424": {
        "iso_code": "si",
        "exit": "Izhod",
        "position": "Položaj",
        "run_at_startup": "Zaženi ob zagonu",
        "about": "O programu",
        "top_left": "Zgoraj Levo",
        "bottom_left": "Spodaj Levo",
        "top_right": "Zgoraj Desno",
        "bottom_right": "Spodaj Desno",
        "top_center": "Zgoraj Sredina",
        "bottom_center": "Spodaj Sredina"
    },
    "0x0420": {
        "iso_code": "pk",
        "exit": "باہر نکلیں",
        "position": "پوزیشن",
        "run_at_startup": "اسٹارٹ اپ پر چلائیں",
        "about": "کے بارے میں",
        "top_left": "اوپر بائیں",
        "bottom_left": "نیچے بائیں",
        "top_right": "اوپر دائیں",
        "bottom_right": "نیچے دائیں",
        "top_center": "اوپر مرکز",
        "bottom_center": "نیچے مرکز"
    },
    "0x0437": {
        "iso_code": "ge",
        "exit": "გასვლა",
        "position": "პოზიცია",
        "run_at_startup": "გაშვება ჩართვისას",
        "about": "შესახებ",
        "top_left": "ზედა მარცხენა",
        "bottom_left": "ქვედა მარცხენა",
        "top_right": "ზედა მარჯვენა",
        "bottom_right": "ქვედა მარჯვენა",
        "top_center": "ზედა ცენტრი",
        "bottom_center": "ქვედა ცენტრი"
    },
    "0x040D": {
        "iso_code": "il",
        "exit": "יציאה",
        "position": "מיקום",
        "run_at_startup": "הפעל בעת הפעלה",
        "about": "אודות",
        "top_left": "למעלה שמאל",
        "bottom_left": "למטה שמאל",
        "top_right": "למעלה ימין",
        "bottom_right": "למטה ימין",
        "top_center": "למעלה מרכז",
        "bottom_center": "למטה מרכז"
    },
    "0x0461": {
        "iso_code": "np",
        "exit": "बाहिर निस्कनुहोस्",
        "position": "स्थान",
        "run_at_startup": "सुरुमा चलाउनुहोस्",
        "about": "बारेमा",
        "top_left": "माथि बायाँ",
        "bottom_left": "तल बायाँ",
        "top_right": "माथि दायाँ",
        "bottom_right": "तल दायाँ",
        "top_center": "माथि केन्द्र",
        "bottom_center": "तल केन्द्र"
    },
    "0x0429": {
        "iso_code": "ir",
        "exit": "خروج",
        "position": "موقعیت",
        "run_at_startup": "اجرا در هنگام راه‌اندازی",
        "about": "درباره",
        "top_left": "بالا چپ",
        "bottom_left": "پایین چپ",
        "top_right": "بالا راست",
        "bottom_right": "پایین راست",
        "top_center": "بالا وسط",
        "bottom_center": "پایین وسط"
    },
    "0x043F": {
        "iso_code": "kz",
        "exit": "Шығу",
        "position": "Позиция",
        "run_at_startup": "Іске қосу кезінде іске қосу",
        "about": "Туралы",
        "top_left": "Жоғары Сол",
        "bottom_left": "Төмен Сол",
        "top_right": "Жоғары Оң",
        "bottom_right": "Төмен Оң",
        "top_center": "Жоғары Орта",
        "bottom_center": "Төмен Орта"
    },
    "0x0440": {
        "iso_code": "kg",
        "exit": "Чыгуу",
        "position": "Орду",
        "run_at_startup": "Баштоодо иштетүү",
        "about": "Жөнүндө",
        "top_left": "Жогорку Сол",
        "bottom_left": "Төмөнкү Сол",
        "top_right": "Жогорку Оң",
        "bottom_right": "Төмөнкү Оң",
        "top_center": "Жогорку Орто",
        "bottom_center": "Төмөнкү Орто"
    },
    "0x042F": {
        "iso_code": "mk",
        "exit": "Излез",
        "position": "Позиција",
        "run_at_startup": "Стартувај при стартување",
        "about": "За програмата",
        "top_left": "Горе Лево",
        "bottom_left": "Долу Лево",
        "top_right": "Горе Десно",
        "bottom_right": "Долу Десно",
        "top_center": "Горе Центар",
        "bottom_center": "Долу Центар"
    },
    "0x041E": {
        "iso_code": "th",
        "exit": "ออก",
        "position": "ตำแหน่ง",
        "run_at_startup": "เรียกใช้เมื่อเริ่มต้น",
        "about": "เกี่ยวกับ",
        "top_left": "บนซ้าย",
        "bottom_left": "ล่างซ้าย",
        "top_right": "บนขวา",
        "bottom_right": "ล่างขวา",
        "top_center": "บนกลาง",
        "bottom_center": "ล่างกลาง"
    },
    "0x0442": {
        "iso_code": "tm",
        "exit": "Çykyş",
        "position": "Ýerleşişi",
        "run_at_startup": "Başlangyçda işe giriz",
        "about": "Hakynda",
        "top_left": "Ýokary Çep",
        "bottom_left": "Aşaky Çep",
        "top_right": "Ýokary Sag",
        "bottom_right": "Aşaky Sag",
        "top_center": "Ýokary Merkez",
        "bottom_center": "Aşaky Merkez"
    }
   
}

